package com.freesic.app;

import android.Manifest;
import android.app.*;
import android.content.*;
import android.content.res.ColorStateList;
import android.graphics.*;
import android.graphics.drawable.GradientDrawable;
import android.media.audiofx.Equalizer;
import android.net.Uri;
import android.os.*;
import android.text.*;
import android.view.*;
import android.view.inputmethod.InputMethodManager;
import android.widget.*;
import androidx.media3.common.*;
import androidx.media3.common.util.UnstableApi;
import androidx.media3.session.*;
import androidx.media3.session.MediaController;
import androidx.activity.ComponentActivity;
import androidx.activity.OnBackPressedCallback;
import androidx.media3.ui.PlayerView;
import com.google.common.util.concurrent.ListenableFuture;
import java.io.*;
import java.nio.charset.StandardCharsets;
import java.util.*;
import java.util.concurrent.*;

@UnstableApi
public final class MainActivity extends ComponentActivity {
    private static final int BG=0xff0D1929,CARD=0xff162238,INK=0xffF4F7FC,MUTED=0xff9BAEC8,BLUE=0xff59A8FA;
    private final ExecutorService io=Executors.newSingleThreadExecutor();
    private final Handler handler=new Handler(Looper.getMainLooper());
    private Store store;private List<Track> library=new ArrayList<>(),shown=new ArrayList<>();
    private final List<String> groups=new ArrayList<>();
    private String section="Biblioteca",category="Músicas",group=null,query="",pendingLyrics="",pendingOpen="";
    private boolean loaded=false,scanning=false,started=false,dragging=false;
    private MediaController controller;private ListenableFuture<MediaController> future;
    private LinearLayout root,content,mini,nav,appHeader;
    private BrandView previousCover,nextCover;private android.animation.ValueAnimator trackMotion;
    private PlayerGestureLayout playerSurface;private FrameLayout playerMedia;private Track visualTrack;private int pendingTrackDirection;private boolean closingPlayer;
    private AlertDialog gainWarning;
    private PopupWindow quickVolume;private SeekBar quickLevel,quickGain;private TextView quickLevelText,quickGainText;private boolean adjustingQuickVolume;
    private final Map<String,Integer> groupCounts=new HashMap<>();private final Map<String,Track> groupCovers=new HashMap<>();
    private final Runnable hideQuickVolume=()->{if(quickVolume!=null&&!adjustingQuickVolume)quickVolume.dismiss();};private TextView miniTitle,miniSub,count;
    private ProgressBar miniProgress;private String pendingArtwork="";private BrandView miniArt;private Button miniPlay;private ListView list;private EditText search;private TrackAdapter adapter;
    private TextView emptyTitle,emptyHelp;private Button emptyAccess,emptyFiles;
    private Dialog playerDialog;private TextView playerTitle,playerArtist,elapsed,total,playerStatus,lyricText;
    private Button playerPlay,repeat,shuffle,favorite;private SeekBar seek;private BrandView cover;private PlayerView video;
    private String displayedUri="";private List<MusicLogic.LyricLine> lyricLines=Collections.emptyList();private int lastLyric=-2;
    private boolean scanAgain=false;
    private final Runnable rescan=()->scan();
    private final android.database.ContentObserver mediaObserver=new android.database.ContentObserver(handler){@Override public void onChange(boolean self,Uri uri){handler.removeCallbacks(rescan);handler.postDelayed(rescan,600);}};
    private final Runnable progress=new Runnable(){public void run(){updatePlayback();handler.postDelayed(this,500);}};
    @Override public void onCreate(Bundle state){
        super.onCreate(state);store=new Store(this);
        getOnBackPressedDispatcher().addCallback(this,new OnBackPressedCallback(true){public void handleOnBackPressed(){if(group!=null){group=null;render();}else if(!section.equals("Biblioteca")){section="Biblioteca";render();}else{setEnabled(false);getOnBackPressedDispatcher().onBackPressed();setEnabled(true);}}});
        if(state!=null){section=state.getString("section","Biblioteca");category=state.getString("category","Músicas");group=state.getString("group");pendingLyrics=state.getString("pendingLyrics","");pendingArtwork=state.getString("pendingArtwork","");}
        getWindow().setStatusBarColor(BG);getWindow().setNavigationBarColor(BG);build();scan();acceptIntent(getIntent());setVolumeControlStream(android.media.AudioManager.STREAM_MUSIC);
        getContentResolver().registerContentObserver(android.provider.MediaStore.Audio.Media.EXTERNAL_CONTENT_URI,true,mediaObserver);
        getContentResolver().registerContentObserver(android.provider.MediaStore.Video.Media.EXTERNAL_CONTENT_URI,true,mediaObserver);
        if(!Library.permission(this,false)&&!store.prefs.getBoolean("audio_permission_requested",false))handler.postDelayed(()->{if(!isFinishing())requestLibrary();},450);
    }
    @Override protected void onSaveInstanceState(Bundle b){super.onSaveInstanceState(b);b.putString("section",section);b.putString("category",category);b.putString("group",group);b.putString("pendingLyrics",pendingLyrics);b.putString("pendingArtwork",pendingArtwork);}
    @Override protected void onNewIntent(Intent i){super.onNewIntent(i);setIntent(i);acceptIntent(i);if(i.getBooleanExtra("show_player",false)){i.removeExtra("show_player");showPlayer();}}
    private void acceptIntent(Intent i){if(i!=null&&Intent.ACTION_VIEW.equals(i.getAction())&&i.getData()!=null){Uri uri=i.getData();if(MusicLogic.localUri(uri.toString()))importTrack(uri,true);else toast("Escolha um arquivo de áudio ou vídeo local");}}
    @Override protected void onStart(){super.onStart();started=true;if(loaded)scan();
        SessionToken token=new SessionToken(this,new ComponentName(this,PlaybackService.class));
        future=new MediaController.Builder(this,token).buildAsync();ListenableFuture<MediaController> request=future;
        request.addListener(()->{if(!started||future!=request)return;try{controller=request.get();controller.addListener(new Player.Listener(){
            @Override public void onEvents(Player player,Player.Events events){updatePlayback();}
            @Override public void onPlayerError(PlaybackException error){toast("Não foi possível tocar. Verifique se o arquivo existe e se o formato é compatível.");}
        });if(video!=null)video.setPlayer(controller);if(!pendingOpen.isEmpty()){String uri=pendingOpen;pendingOpen="";for(Track t:store.tracks("imports"))if(t.uri.equals(uri)){play(Collections.singletonList(t),0);break;}}
            if(getIntent().getBooleanExtra("show_player",false)){getIntent().removeExtra("show_player");showPlayer();}updatePlayback();
        }catch(Exception e){toast("Não foi possível conectar ao player. Reabra o Freesic.");}},this::runOnUiThread);
        handler.post(progress);
    }
    @Override protected void onStop(){started=false;handler.removeCallbacks(progress);if(video!=null)video.setPlayer(null);if(future!=null)MediaController.releaseFuture(future);future=null;controller=null;if(quickVolume!=null)quickVolume.dismiss();super.onStop();}
    @Override protected void onDestroy(){if(gainWarning!=null)gainWarning.dismiss();getContentResolver().unregisterContentObserver(mediaObserver);handler.removeCallbacksAndMessages(null);io.shutdown();super.onDestroy();}
    private int dp(float n){return (int)(n*getResources().getDisplayMetrics().density+.5f);}
    private TextView text(String value,int size,int color,boolean bold){TextView t=new TextView(this);t.setText(value);t.setTextSize(size);t.setTextColor(color);t.setTypeface(getResources().getFont(bold?R.font.inter_bold:R.font.inter_regular));t.setIncludeFontPadding(false);return t;}
    private LinearLayout col(){LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.VERTICAL);return l;}
    private LinearLayout row(){LinearLayout l=new LinearLayout(this);l.setGravity(Gravity.CENTER_VERTICAL);return l;}
    private GradientDrawable bg(int color,int radius){GradientDrawable d=new GradientDrawable();d.setColor(color);d.setCornerRadius(dp(radius));return d;}
    private Button button(String label,boolean accent,Runnable click){Button b=Icons.has(label)?new Icons(this):new Button(this);b.setText(label);b.setTextSize(13);b.setAllCaps(false);b.setTextColor(accent?BG:INK);b.setTypeface(getResources().getFont(R.font.inter_medium));b.setStateListAnimator(null);b.setElevation(0);b.setBackground(new android.graphics.drawable.RippleDrawable(ColorStateList.valueOf(0x3365ADFF),bg(accent?BLUE:CARD,16),null));b.setMinHeight(dp(48));b.setMinimumHeight(dp(48));b.setMinWidth(0);b.setMinimumWidth(0);b.setPadding(dp(14),dp(8),dp(14),dp(8));b.setOnClickListener(v->click.run());b.setOnTouchListener((v,event)->{int action=event.getActionMasked();if(action==MotionEvent.ACTION_DOWN)v.animate().scaleX(.92f).scaleY(.92f).setDuration(MotionCurves.duration(150)).setInterpolator(MotionCurves.TRACK).start();else if(action==MotionEvent.ACTION_UP||action==MotionEvent.ACTION_CANCEL)v.animate().scaleX(1).scaleY(1).setDuration(MotionCurves.duration(150)).setInterpolator(MotionCurves.TRACK).start();return false;});b.setContentDescription(label);return b;}
    private void gap(LinearLayout l,int h){View v=new View(this);l.addView(v,new LinearLayout.LayoutParams(1,dp(h)));}
    private void addWeighted(LinearLayout l,View v){l.addView(v,new LinearLayout.LayoutParams(0,ViewGroup.LayoutParams.WRAP_CONTENT,1));}
    private void label(TextView view,CharSequence value){if(!value.toString().contentEquals(view.getText()))view.setText(value);}
    private void toast(String message){Toast.makeText(this,message,Toast.LENGTH_LONG).show();}
    private Button icon(String name,String description,Runnable click){Button b=button(name.startsWith("@")||Icons.has(name)?name:"@"+name,false,click);b.setContentDescription(description);b.setBackgroundColor(Color.TRANSPARENT);b.setPadding(0,0,0,0);return b;}
    private void line(LinearLayout parent,int color){View v=new View(this);v.setBackgroundColor(color);parent.addView(v,new LinearLayout.LayoutParams(-1,dp(1)));}
    private void build(){
        root=col();root.setBackground(UiTheme.background());root.setOnApplyWindowInsetsListener((v,in)->{root.setPadding(0,in.getSystemWindowInsetTop(),0,in.getSystemWindowInsetBottom());return in;});setContentView(root);
        LinearLayout header=row();header.setPadding(dp(22),0,dp(12),0);TextView brand=text("freesic",24,INK,true);android.text.SpannableString word=new android.text.SpannableString("freesic");word.setSpan(new android.text.style.ForegroundColorSpan(BLUE),1,7,0);brand.setText(word);addWeighted(header,brand);header.addView(icon("search","Buscar músicas",()->{if(search==null){section="Biblioteca";group=null;render();}search.requestFocus();((InputMethodManager)getSystemService(INPUT_METHOD_SERVICE)).showSoftInput(search,InputMethodManager.SHOW_IMPLICIT);}),new LinearLayout.LayoutParams(dp(44),dp(48)));header.addView(icon("more","Mais opções",this::libraryOptions),new LinearLayout.LayoutParams(dp(36),dp(48)));appHeader=header;appHeader.setPadding(0,0,0,0);appHeader.setLayoutParams(new LinearLayout.LayoutParams(-1,dp(64)));ImageView logo=new ImageView(this);logo.setImageResource(R.drawable.brand_logo);logo.setContentDescription("Freesic");LinearLayout.LayoutParams logoSize=new LinearLayout.LayoutParams(dp(32),dp(32));logoSize.rightMargin=dp(10);header.addView(logo,0,logoSize);
        content=col();content.setPadding(dp(22),0,dp(22),0);root.addView(content,new LinearLayout.LayoutParams(-1,0,1));
        LinearLayout dock=col();dock.setBackgroundColor(0xff15253A);miniProgress=new ProgressBar(this,null,android.R.attr.progressBarStyleHorizontal);miniProgress.setMax(1000);miniProgress.setProgressTintList(ColorStateList.valueOf(BLUE));miniProgress.setProgressBackgroundTintList(ColorStateList.valueOf(0xff263D58));dock.addView(miniProgress,new LinearLayout.LayoutParams(-1,dp(2)));
        mini=row();mini.setPadding(dp(18),dp(7),dp(10),dp(7));mini.setOnClickListener(v->showPlayer());installMiniSwipe(mini);mini.setContentDescription("Abrir player");miniArt=new BrandView(this);mini.addView(miniArt,new LinearLayout.LayoutParams(dp(40),dp(40)));LinearLayout metadata=col();metadata.setPadding(dp(14),0,dp(6),0);miniTitle=text("Escolha uma música",13,INK,false);miniTitle.setSingleLine();miniTitle.setEllipsize(TextUtils.TruncateAt.END);miniSub=text("Sua biblioteca local",11,MUTED,false);miniSub.setSingleLine();metadata.addView(miniTitle);gap(metadata,4);metadata.addView(miniSub);addWeighted(mini,metadata);miniPlay=icon("▶","Reproduzir ou pausar",this::togglePlay);mini.addView(miniPlay,new LinearLayout.LayoutParams(dp(44),dp(44)));mini.addView(icon("up","Abrir player",this::showPlayer),new LinearLayout.LayoutParams(dp(34),dp(44)));dock.addView(mini,new LinearLayout.LayoutParams(-1,dp(56)));root.addView(dock);
        nav=row();nav.setPadding(dp(10),0,dp(10),0);for(String n:new String[]{"Biblioteca","Playlists","Favoritos","Ajustes"}){Button b=button(n,false,()->{section=n;group=null;query="";hideKeyboard();render();});b.setTextSize(11);b.setPadding(0,dp(8),0,dp(6));android.graphics.drawable.Drawable d=Icons.named(this,n.equals("Biblioteca")?"music":n.equals("Playlists")?"playlist":n.equals("Favoritos")?"heart":"settings");d.setBounds(0,0,dp(23),dp(23));b.setCompoundDrawables(null,d,null,null);b.setCompoundDrawablePadding(dp(5));nav.addView(b,new LinearLayout.LayoutParams(0,dp(64),1));}root.addView(nav);render();
    }
    private void libraryOptions(){new VolumeDialogBuilder(this).setTitle("Biblioteca").setItems(new String[]{"Ordenar músicas","Atualizar biblioteca","Escolher arquivos","Vídeos","Recentes","Ajustes"},(d,w)->{if(w==0)sortDialog();else if(w==1){scan();toast("Biblioteca atualizada");}else if(w==2)pickMedia();else if(w==5){section="Ajustes";group=null;render();}else{section="Biblioteca";group=null;category=w==3?"Vídeos":"Recentes";render();if(w==3&&!Library.permission(this,true))requestLibrary();}}).show();}
    private void heading(String title,String ignored){gap(content,4);TextView h=text(title,38,INK,true);h.setMaxLines(2);content.addView(h);gap(content,10);}
    private void render(){
        content.removeAllViews();list=null;count=null;search=null;
        for(int i=0;i<nav.getChildCount();i++){Button b=(Button)nav.getChildAt(i);boolean active=b.getText().toString().equals(section);b.setTextColor(active?BLUE:MUTED);b.setBackgroundColor(Color.TRANSPARENT);b.setCompoundDrawableTintList(ColorStateList.valueOf(active?BLUE:MUTED));}
        if(section.equals("Ajustes")){settings();return;}if(section.equals("Playlists")&&group==null){playlists();return;}
        if(group!=null){LinearLayout back=row();back.addView(icon("@down","Voltar",()->{group=null;render();}),new LinearLayout.LayoutParams(dp(36),dp(40)));back.addView(text(section.equals("Playlists")?"PLAYLIST":"BIBLIOTECA",11,MUTED,false));content.addView(back);}
        heading(group!=null?group:section.equals("Biblioteca")?(category.equals("Vídeos")?"Vídeos":category.equals("Recentes")?"Recentes":"Biblioteca"):section,"");
        LinearLayout searchBox=row();searchBox.setBackground(bg(0xff1A2A40,18));searchBox.setPadding(dp(16),0,dp(12),0);android.widget.ImageView magnifier=new android.widget.ImageView(this);magnifier.setImageDrawable(Icons.named(this,"search"));magnifier.setImageTintList(ColorStateList.valueOf(MUTED));searchBox.addView(magnifier,new LinearLayout.LayoutParams(dp(20),dp(20)));search=new EditText(this);search.setSingleLine();search.setTextColor(INK);search.setHintTextColor(MUTED);search.setTypeface(getResources().getFont(R.font.inter_regular));search.setTextSize(13);search.setHint("Buscar músicas, artistas, álbuns...");search.setBackgroundColor(Color.TRANSPARENT);search.setPadding(dp(12),0,0,0);search.setText(query);searchBox.addView(search,new LinearLayout.LayoutParams(0,-1,1));content.addView(searchBox,new LinearLayout.LayoutParams(-1,dp(50)));
        search.addTextChangedListener(new TextWatcher(){public void beforeTextChanged(CharSequence s,int a,int c,int n){}public void onTextChanged(CharSequence s,int a,int b,int c){query=s.toString();filter();}public void afterTextChanged(Editable e){}});
        if(section.equals("Biblioteca")&&group==null&&!category.equals("Vídeos")&&!category.equals("Recentes")){gap(content,8);LinearLayout tabs=row();for(String cat:new String[]{"Músicas","Álbuns","Artistas","Pastas"}){LinearLayout item=col();Button b=button(cat,false,()->{category=cat;group=null;render();});b.setPadding(0,0,0,0);b.setTextColor(category.equals(cat)?BLUE:MUTED);b.setBackgroundColor(Color.TRANSPARENT);b.setTypeface(getResources().getFont(category.equals(cat)?R.font.inter_medium:R.font.inter_regular));item.addView(b,new LinearLayout.LayoutParams(-1,dp(46)));View underline=new View(this);underline.setBackground(bg(category.equals(cat)?BLUE:Color.TRANSPARENT,2));LinearLayout.LayoutParams ul=new LinearLayout.LayoutParams(-1,dp(2));ul.setMargins(0,0,dp(16),0);item.addView(underline,ul);tabs.addView(item,new LinearLayout.LayoutParams(0,-2,1));}content.addView(tabs);line(content,0xff203249);}else gap(content,12);
        LinearLayout tools=row();count=text("Carregando…",15,MUTED,false);addWeighted(tools,count);Button all=button("Reproduzir tudo",true,()->{if(!shown.isEmpty())play(shown,0);else toast("Não há músicas nesta seleção");});all.setTextSize(13);android.graphics.drawable.Drawable play=Icons.named(this,"play");play.setTint(BG);play.setBounds(0,0,dp(17),dp(17));all.setCompoundDrawables(play,null,null,null);all.setCompoundDrawablePadding(dp(8));all.setMinHeight(0);all.setMinimumHeight(0);tools.addView(all,new LinearLayout.LayoutParams(dp(170),dp(40)));content.addView(tools,new LinearLayout.LayoutParams(-1,dp(70)));
        if(section.equals("Playlists")&&group!=null){Button add=button("Adicionar músicas",false,this::selectPlaylistTracks);content.addView(add,new LinearLayout.LayoutParams(-1,dp(44)));gap(content,12);}
        FrameLayout frame=new FrameLayout(this);list=new ListView(this);list.setDivider(null);list.setCacheColorHint(Color.TRANSPARENT);list.setVerticalScrollBarEnabled(false);adapter=new TrackAdapter();list.setAdapter(adapter);frame.addView(list,new FrameLayout.LayoutParams(-1,-1));LinearLayout empty=col();empty.setGravity(Gravity.CENTER);empty.setPadding(dp(12),dp(10),dp(12),dp(10));emptyTitle=text("Sua música começa aqui",20,INK,true);emptyTitle.setGravity(Gravity.CENTER);empty.addView(emptyTitle);gap(empty,12);emptyHelp=text("Permita o acesso às músicas do aparelho.",14,MUTED,false);emptyHelp.setGravity(Gravity.CENTER);empty.addView(emptyHelp);gap(empty,18);emptyAccess=button("Acessar biblioteca",true,this::requestLibrary);empty.addView(emptyAccess);gap(empty,10);emptyFiles=button("Escolher arquivos",false,this::pickMedia);empty.addView(emptyFiles);frame.addView(empty,new FrameLayout.LayoutParams(-1,-1));list.setEmptyView(empty);content.addView(frame,new LinearLayout.LayoutParams(-1,0,1));filter();installChrome(frame,list);
    }
    private void filter(){
        if(list==null)return;shown=new ArrayList<>();groups.clear();groupCounts.clear();groupCovers.clear();String q=MusicLogic.normalize(query);Set<String> favorites=store.favorites();List<String> playlist=section.equals("Playlists")&&group!=null?store.playlist(group):null;
        List<Track> source=category.equals("Recentes")&&section.equals("Biblioteca")?store.tracks("history"):library;
        for(Track t:source){
            if(section.equals("Favoritos")&&!favorites.contains(t.uri))continue;
            if(playlist!=null&&!playlist.contains(t.uri))continue;
            if(section.equals("Biblioteca")&&category.equals("Vídeos")&&!t.video)continue;
            if(section.equals("Biblioteca")&&!category.equals("Vídeos")&&!category.equals("Recentes")&&t.video)continue;
            if(group!=null&&section.equals("Biblioteca")&&!groupName(t).equals(group))continue;
            if(!MusicLogic.normalize(t.title+" "+t.artist+" "+t.album+" "+t.folder).contains(q))continue;shown.add(t);
        }
        if(playlist!=null)shown.sort(Comparator.comparingInt(t->playlist.indexOf(t.uri)));
        else if(!category.equals("Recentes")){
            int sort=store.prefs.getInt("sort",0);Comparator<Track> cmp=sort==1?Comparator.comparingLong((Track t)->t.added).reversed():sort==2?Comparator.comparing(t->MusicLogic.normalize(t.artist)):sort==3?Comparator.comparingLong((Track t)->t.duration).reversed():Comparator.comparing(t->MusicLogic.normalize(t.title));shown.sort(cmp);
        }
        if(section.equals("Biblioteca")&&group==null&&Arrays.asList("Álbuns","Artistas","Pastas").contains(category)){
            TreeSet<String> names=new TreeSet<>(String.CASE_INSENSITIVE_ORDER);for(Track t:shown){String key=groupName(t);names.add(key);groupCounts.put(key,groupCounts.getOrDefault(key,0)+1);if(!groupCovers.containsKey(key))groupCovers.put(key,t);}groups.addAll(names);
        }
        boolean collection=section.equals("Playlists")||section.equals("Favoritos")||category.equals("Recentes");
        emptyTitle.setText(!q.isEmpty()?"Nenhum resultado":collection?"Sua coleção começa aqui":"Um espaço para o seu som");
        emptyHelp.setText(!q.isEmpty()?"Tente outro título, artista ou álbum.":collection?"Use o menu das músicas para organizar suas faixas. Seu histórico aparece conforme você escuta.":"Libere sua biblioteca ou escolha arquivos locais.\nSuas músicas não saem do aparelho.");
        emptyAccess.setVisibility(q.isEmpty()&&!collection&&!Library.permission(this,category.equals("Vídeos"))?View.VISIBLE:View.GONE);emptyFiles.setVisibility(q.isEmpty()&&!collection?View.VISIBLE:View.GONE);
        count.setText(scanning?"ATUALIZANDO…":groups.isEmpty()?shown.size()+(category.equals("Vídeos")?" vídeos":" músicas"):groups.size()+" coleções");adapter.notifyDataSetChanged();
    }
    private String groupName(Track t){return category.equals("Álbuns")?t.album:category.equals("Artistas")?t.artist:t.folder;}
    private final class TrackRow {
        LinearLayout row;BrandView art;TextView title,detail;Button more;
        TrackRow(){row=row();row.setPadding(0,dp(4),0,dp(4));art=new BrandView(MainActivity.this);row.addView(art,new LinearLayout.LayoutParams(dp(58),dp(58)));LinearLayout info=col();info.setPadding(dp(20),0,dp(8),0);title=text("",16,INK,false);title.setTypeface(getResources().getFont(R.font.inter_medium));title.setSingleLine();title.setEllipsize(TextUtils.TruncateAt.END);info.addView(title);gap(info,5);detail=text("",13,MUTED,false);detail.setSingleLine();detail.setEllipsize(TextUtils.TruncateAt.END);info.addView(detail);addWeighted(row,info);more=icon("more","Opções da música",()->{});more.setFocusable(false);row.addView(more,new LinearLayout.LayoutParams(dp(44),dp(48)));row.setTag(this);}
    }
    private final class TrackAdapter extends BaseAdapter{
        public int getCount(){return groups.isEmpty()?shown.size():groups.size();}public Object getItem(int p){return groups.isEmpty()?shown.get(p):groups.get(p);}public long getItemId(int p){return p;}
        public View getView(int position,View reused,ViewGroup parent){
            TrackRow h=reused!=null&&reused.getTag() instanceof TrackRow?(TrackRow)reused.getTag():new TrackRow();
            boolean grouping=!groups.isEmpty();Track track=grouping?groupCovers.get(groups.get(position)):shown.get(position);String name=grouping?groups.get(position):track.title;
            h.art.track(track);h.title.setText(name);h.detail.setText(grouping?groupCounts.getOrDefault(name,0)+" faixas":track.artist);
            h.more.setVisibility(grouping?View.GONE:View.VISIBLE);h.more.setContentDescription("Opções de "+name);h.more.setOnClickListener(v->{if(track!=null)trackMenu(track);});
            h.row.setOnClickListener(v->{if(grouping){group=name;render();}else play(shown,position);});h.row.setOnLongClickListener(v->{if(!grouping){trackMenu(track);return true;}return false;});return h.row;
        }
    }
    private void sortDialog(){new VolumeDialogBuilder(this).setTitle("Ordenar por").setSingleChoiceItems(new String[]{"Título","Adicionadas recentemente","Artista","Duração"},store.prefs.getInt("sort",0),(d,w)->{store.prefs.edit().putInt("sort",w).apply();filter();d.dismiss();}).show();}
    private void requestLibrary(){store.prefs.edit().putBoolean("audio_permission_requested",true).apply();ArrayList<String> perms=new ArrayList<>();if(Build.VERSION.SDK_INT>=33){perms.add(Manifest.permission.READ_MEDIA_AUDIO);if(category.equals("Vídeos")){perms.add(Manifest.permission.READ_MEDIA_VIDEO);if(Build.VERSION.SDK_INT>=34)perms.add(Manifest.permission.READ_MEDIA_VISUAL_USER_SELECTED);}}else perms.add(Manifest.permission.READ_EXTERNAL_STORAGE);requestPermissions(perms.toArray(new String[0]),40);}
    @Override public void onRequestPermissionsResult(int request,String[] permissions,int[] results){super.onRequestPermissionsResult(request,permissions,results);if(request==40)scan();}
    private void scan(){if(isDestroyed())return;if(scanning){scanAgain=true;return;}scanning=true;filter();io.execute(()->{try{List<Track> result=Library.scan(this,store);runOnUiThread(()->{if(isDestroyed())return;library=result;scanning=false;loaded=true;filter();if(scanAgain){scanAgain=false;scan();}});}catch(Exception e){runOnUiThread(()->{scanning=false;filter();toast("Não foi possível ler a biblioteca. Tente escolher os arquivos manualmente.");});}});}
    private void pickMedia(){Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT).setType("*/*").putExtra(Intent.EXTRA_MIME_TYPES,new String[]{"audio/*","video/*"}).putExtra(Intent.EXTRA_ALLOW_MULTIPLE,true).addCategory(Intent.CATEGORY_OPENABLE);startActivityForResult(i,50);}
    private void importTrack(Uri uri,boolean play){
        io.execute(()->{try{Track t=Library.importUri(this,uri);store.addImport(t);runOnUiThread(()->{if(isDestroyed())return;library.removeIf(x->x.uri.equals(t.uri));library.add(t);filter();if(play){if(controller==null)pendingOpen=t.uri;else play(Collections.singletonList(t),0);}else toast("Adicionado: "+t.title);});}catch(Exception e){runOnUiThread(()->toast("Não foi possível abrir o arquivo selecionado"));}});
    }
    private void play(List<Track> tracks,int index){
        if(controller==null){toast("Conectando ao player. Tente novamente em instantes.");return;}if(tracks.isEmpty())return;
        List<MediaItem> items=new ArrayList<>();for(Track t:tracks)items.add(t.item());controller.setMediaItems(items,index,0);controller.prepare();controller.play();hideKeyboard();updatePlayback();if(tracks.get(index).video)showPlayer();
    }
    private void hideKeyboard(){View f=getCurrentFocus();if(f!=null){((InputMethodManager)getSystemService(INPUT_METHOD_SERVICE)).hideSoftInputFromWindow(f.getWindowToken(),0);f.clearFocus();}}
    private void togglePlay(){if(controller==null){toast("Conectando ao player…");return;}if(controller.isPlaying())controller.pause();else if(controller.getMediaItemCount()>0){if(controller.getPlaybackState()==Player.STATE_IDLE)controller.prepare();if(controller.getPlaybackState()==Player.STATE_ENDED)controller.seekToDefaultPosition();controller.play();}else if(!shown.isEmpty())play(shown,0);else toast("Adicione músicas à biblioteca para começar");}
    private Track current(){return controller==null||controller.getCurrentMediaItem()==null?null:Track.item(controller.getCurrentMediaItem());}
    private void trackMenu(Track t){
        ArrayList<String> actions=new ArrayList<>(Arrays.asList("Tocar agora","Tocar a seguir","Adicionar à fila",store.favorites().contains(t.uri)?"Remover dos favoritos":"Adicionar aos favoritos","Adicionar a uma playlist","Compartilhar arquivo","Detalhes"));
        actions.add("Escolher capa");if(section.equals("Playlists")&&group!=null)actions.add("Remover desta playlist");
        new VolumeDialogBuilder(this).setTitle(t.title).setItems(actions.toArray(new String[0]),(d,w)->{
            switch(w){case 0:play(Collections.singletonList(t),0);break;case 1:case 2:if(controller!=null){int at=w==1?Math.min(controller.getMediaItemCount(),controller.getCurrentMediaItemIndex()+1):controller.getMediaItemCount();controller.addMediaItem(Math.max(0,at),t.item());toast("Adicionada à fila");}break;
                case 3:store.favorite(t.uri);filter();updatePlayback();break;case 4:addPlaylist(t);break;case 5:share(t);break;
                case 6:new VolumeDialogBuilder(this).setTitle("Detalhes").setMessage(t.title+"\n"+t.artist+"\n"+t.album+"\n\n"+t.folder+"\n"+MusicLogic.time(t.duration)+"\n\n"+t.uri).setPositiveButton("Fechar",null).show();break;
                case 7:pendingArtwork=t.uri;startActivityForResult(new Intent(Intent.ACTION_OPEN_DOCUMENT).setType("image/*").addCategory(Intent.CATEGORY_OPENABLE),54);break;case 8:store.removeFromPlaylist(group,t.uri);filter();break;
            }
        }).show();
    }
    private void share(Track t){try{Intent i=new Intent(Intent.ACTION_SEND).setType(t.video?"video/*":"audio/*").putExtra(Intent.EXTRA_STREAM,Uri.parse(t.uri)).addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION);startActivity(Intent.createChooser(i,"Compartilhar arquivo"));}catch(Exception e){toast("Este arquivo não pode ser compartilhado");}}
    private void playlists(){heading("Playlists","");LinearLayout tools=row();addWeighted(tools,text(store.playlistNames().size()+" coleções",14,MUTED,false));Button create=button("+ Nova playlist",true,()->newPlaylist(null));tools.addView(create,new LinearLayout.LayoutParams(dp(152),dp(42)));content.addView(tools);gap(content,20);ScrollView scroll=new ScrollView(this);LinearLayout grid=col();List<String> names=store.playlistNames();if(names.isEmpty()){TextView help=text("Crie uma playlist para reunir suas favoritas.",15,MUTED,false);help.setGravity(Gravity.CENTER);grid.addView(help);}
        for(int start=0;start<names.size();start+=2){LinearLayout pair=row();pair.setGravity(Gravity.TOP);for(int j=start;j<Math.min(start+2,names.size());j++){String name=names.get(j);LinearLayout card=col();card.setPadding(dp(12),dp(12),dp(12),dp(10));GradientDrawable background=bg(0xff16283E,18);background.setStroke(dp(1),0xff243A54);card.setBackground(background);card.setContentDescription("Abrir playlist "+name);card.setOnClickListener(v->{group=name;render();});List<String> ids=store.playlist(name);List<Track> tracks=new ArrayList<>();for(String id:ids)for(Track t:library)if(t.uri.equals(id)){tracks.add(t);break;}int size=(getResources().getDisplayMetrics().widthPixels-dp(44+14))/2-dp(24);FrameLayout mosaic=new FrameLayout(this);if(tracks.size()<4){BrandView art=new BrandView(this);if(!tracks.isEmpty())art.track(tracks.get(0));mosaic.addView(art,new FrameLayout.LayoutParams(-1,-1));}else for(int k=0;k<4;k++){BrandView art=new BrandView(this);art.track(tracks.get(k));FrameLayout.LayoutParams lp=new FrameLayout.LayoutParams(size/2-dp(1),size/2-dp(1));lp.leftMargin=(k%2)*size/2;lp.topMargin=(k/2)*size/2;mosaic.addView(art,lp);}card.addView(mosaic,new LinearLayout.LayoutParams(-1,size));gap(card,12);TextView title=text(name,16,INK,true);title.setSingleLine();title.setEllipsize(TextUtils.TruncateAt.END);card.addView(title);LinearLayout detail=row();addWeighted(detail,text(ids.size()+" músicas",12,MUTED,false));Button more=icon("more","Opções da playlist "+name,()->new VolumeDialogBuilder(this).setTitle(name).setItems(new String[]{"Adicionar músicas","Excluir playlist"},(d,w)->{if(w==0){group=name;render();selectPlaylistTracks();}else new VolumeDialogBuilder(this).setMessage("Excluir a playlist? As músicas serão mantidas.").setNegativeButton("Cancelar",null).setPositiveButton("Excluir",(a,b)->{store.deletePlaylist(name);render();}).show();}).show());detail.addView(more,new LinearLayout.LayoutParams(dp(32),dp(36)));card.addView(detail);LinearLayout.LayoutParams cp=new LinearLayout.LayoutParams(0,-2,1);if(j%2==0)cp.rightMargin=dp(14);pair.addView(card,cp);}if(pair.getChildCount()==1)pair.addView(new View(this),new LinearLayout.LayoutParams(0,1,1));grid.addView(pair);gap(grid,14);}scroll.addView(grid);content.addView(scroll,new LinearLayout.LayoutParams(-1,0,1));installChrome(scroll,scroll);}
    private void newPlaylist(Track t){EditText input=new EditText(this);input.setSingleLine();input.setHint("Nome da playlist");input.setFilters(new InputFilter[]{new InputFilter.LengthFilter(80)});new VolumeDialogBuilder(this).setTitle("Nova playlist").setView(input).setNegativeButton("Cancelar",null).setPositiveButton("Criar",(d,w)->{String n=input.getText().toString().trim();if(n.isEmpty())return;store.createPlaylist(n);if(t!=null)store.addToPlaylist(n,t);if(section.equals("Playlists"))render();toast("Playlist salva");}).show();}
    private void addPlaylist(Track t){List<String> names=store.playlistNames();names.add(0,"+ Criar playlist");new VolumeDialogBuilder(this).setTitle("Adicionar a uma playlist").setItems(names.toArray(new String[0]),(d,w)->{if(w==0)newPlaylist(t);else{store.addToPlaylist(names.get(w),t);toast("Adicionada a "+names.get(w));}}).show();}
    private void settings(){
        heading("Do seu jeito","Freesic 1.3 · feito para ouvir livre.");ScrollView scroll=new ScrollView(this);LinearLayout items=col();
        TextView privacy=text("100% no seu aparelho",22,BLUE,true);items.addView(privacy);gap(items,10);items.addView(text("Sem anúncios, login ou rastreamento. O Freesic não tem permissão de internet. Seus arquivos e suas escolhas ficam com você.",14,MUTED,false));gap(items,22);
        for(String label:new String[]{"Atualizar biblioteca","Escolher arquivos","Permissões da biblioteca","Volume e amplificação","Equalizador","Temporizador","Exportar playlists e favoritos","Importar backup","Licenças e sobre"}){
            items.addView(button(label,false,()->{switch(label){case "Atualizar biblioteca":scan();toast("Atualizando a biblioteca");break;case "Escolher arquivos":pickMedia();break;case "Permissões da biblioteca":requestLibrary();break;case "Volume e amplificação":volume();break;case "Equalizador":effects();break;case "Temporizador":timer();break;case "Exportar playlists e favoritos":startActivityForResult(new Intent(Intent.ACTION_CREATE_DOCUMENT).setType("application/json").addCategory(Intent.CATEGORY_OPENABLE).putExtra(Intent.EXTRA_TITLE,"freesic-backup.json"),52);break;case "Importar backup":startActivityForResult(new Intent(Intent.ACTION_OPEN_DOCUMENT).setType("*/*").addCategory(Intent.CATEGORY_OPENABLE),53);break;default:about();}}));gap(items,10);
        }items.addView(text("O backup guarda organização e referências aos arquivos, não as músicas. Em outro aparelho, algumas referências podem precisar ser refeitas.",12,MUTED,false));gap(items,18);scroll.addView(items);content.addView(scroll,new LinearLayout.LayoutParams(-1,0,1));installChrome(scroll,scroll);
    }
    private void about(){new VolumeDialogBuilder(this).setTitle("Freesic 1.3.0").setMessage("Sua música. Seu espaço.\n\nUm player independente, feito para sua biblioteca local. Sem anúncios, contas ou rastreamento.\n\nCompatibilidade de áudio, vídeo e efeitos depende dos decodificadores do seu aparelho.").setNeutralButton("Licenças",(d,w)->{try(InputStream in=getAssets().open("third_party_notices.txt")){ByteArrayOutputStream out=new ByteArrayOutputStream();byte[] bytes=new byte[4096];int n;while((n=in.read(bytes))!=-1)out.write(bytes,0,n);ScrollView s=new ScrollView(this);TextView t=text(out.toString("UTF-8"),12,INK,false);t.setPadding(dp(18),dp(12),dp(18),dp(12));s.addView(t);new VolumeDialogBuilder(this).setTitle("Software de terceiros").setView(s).setPositiveButton("Fechar",null).show();}catch(IOException e){toast("Licenças disponíveis no projeto do Freesic");}}).setPositiveButton("Fechar",null).show();}
    private void showPlayer(){
        if(playerDialog!=null&&playerDialog.isShowing())return;Track t=current();if(t==null){toast("Escolha uma música para abrir o player");return;}
        float height=getResources().getDisplayMetrics().heightPixels/getResources().getDisplayMetrics().density;float rhythm=Math.min(1f,height/816f);int width=getResources().getDisplayMetrics().widthPixels;
        playerDialog=new KeyAwareDialog(android.R.style.Theme_Material_NoActionBar);LinearLayout base=col();base.setPadding(dp(26),0,dp(26),dp(32));base.setOnApplyWindowInsetsListener((v,in)->{base.setPadding(dp(26),in.getSystemWindowInsetTop(),dp(26),dp(32)+in.getSystemWindowInsetBottom());return in;});PlayerGestureLayout scroll=new PlayerGestureLayout(this,new PlayerGestureLayout.Callbacks(){public boolean next(int direction){return skipTrack(direction);}public void minimize(){minimizePlayer();}public boolean begin(){if(closingPlayer)return false;if(trackMotion!=null&&trackMotion.isRunning()){trackMotion.cancel();if(cover!=null){cover.setTranslationX(0);cover.setScaleX(1);cover.setScaleY(1);}prepareNeighborCovers();}return true;}});playerSurface=scroll;scroll.setBackground(UiTheme.player());scroll.addView(base);playerDialog.setContentView(scroll);Window win=playerDialog.getWindow();win.setBackgroundDrawableResource(android.R.color.transparent);win.setStatusBarColor(0xff102A45);win.setNavigationBarColor(0xff0D1929);
        LinearLayout top=row();top.addView(icon("down","Voltar à biblioteca",this::minimizePlayer),new LinearLayout.LayoutParams(dp(32),dp(48)));TextView label=text("TOCANDO AGORA",11,INK,false);label.setGravity(Gravity.CENTER);label.setLetterSpacing(.13f);addWeighted(top,label);top.addView(icon("more","Opções de reprodução",this::playerOptions),new LinearLayout.LayoutParams(dp(32),dp(48)));top.getChildAt(0).setTranslationX(-dp(10));top.getChildAt(2).setTranslationX(dp(10));base.addView(top,new LinearLayout.LayoutParams(-1,dp(64)));gap(base,(int)(14*rhythm));
        int size=Math.min((int)(width*.725f*rhythm),dp(Math.max(150,height-515-120*(getResources().getConfiguration().fontScale-1))));FrameLayout media=new FrameLayout(this);playerMedia=media;media.setClipChildren(true);previousCover=new BrandView(this);previousCover.setTag("neighbor-left");media.addView(previousCover,new FrameLayout.LayoutParams(-1,-1));nextCover=new BrandView(this);nextCover.setTag("neighbor-right");media.addView(nextCover,new FrameLayout.LayoutParams(-1,-1));cover=new BrandView(this);scroll.artwork(media);media.addView(cover,new FrameLayout.LayoutParams(-1,-1));video=new PlayerView(this);video.setUseController(true);video.setPlayer(controller);media.addView(video,new FrameLayout.LayoutParams(-1,-1));LinearLayout.LayoutParams art=new LinearLayout.LayoutParams(size,size);art.gravity=Gravity.CENTER_HORIZONTAL;base.addView(media,art);gap(base,(int)(44*rhythm));
        LinearLayout titleRow=row();LinearLayout labels=col();playerTitle=text("",27,INK,true);playerTitle.setMaxLines(2);playerTitle.setEllipsize(TextUtils.TruncateAt.END);labels.addView(playerTitle);gap(labels,8);playerArtist=text("",17,MUTED,false);playerArtist.setMaxLines(1);playerArtist.setEllipsize(TextUtils.TruncateAt.END);labels.addView(playerArtist);addWeighted(titleRow,labels);favorite=icon("♡","Alternar favorito",()->{Track now=current();if(now!=null){store.favorite(now.uri);updatePlayback();filter();}});favorite.setBackground(bg(0xff1B2D45,50));titleRow.addView(favorite,new LinearLayout.LayoutParams(dp(50),dp(50)));base.addView(titleRow);gap(base,(int)(20*rhythm));
        seek=new SeekBar(this);seek.setMax(1000);seek.setProgressTintList(ColorStateList.valueOf(BLUE));seek.setProgressBackgroundTintList(ColorStateList.valueOf(0xff36506E));seek.setThumbTintList(ColorStateList.valueOf(BLUE));styleSlider(seek,12,2);seek.setContentDescription("Posição da reprodução");base.addView(seek,new LinearLayout.LayoutParams(-1,dp(48)));seek.setOnSeekBarChangeListener(new SeekBar.OnSeekBarChangeListener(){public void onStartTrackingTouch(SeekBar s){dragging=true;}public void onProgressChanged(SeekBar s,int p,boolean user){if(user&&controller!=null)label(elapsed,MusicLogic.time(Math.max(0,controller.getDuration())*p/1000));}public void onStopTrackingTouch(SeekBar s){if(controller!=null&&controller.getDuration()>0)controller.seekTo(controller.getDuration()*s.getProgress()/1000);dragging=false;}});
        LinearLayout times=row();elapsed=text("0:00",12,INK,false);total=text("0:00",12,INK,false);addWeighted(times,elapsed);times.addView(total);base.addView(times);gap(base,(int)(22*rhythm));
        LinearLayout controls=row();shuffle=icon("⇄","Alternar reprodução aleatória",()->{if(controller!=null){controller.setShuffleModeEnabled(!controller.getShuffleModeEnabled());updatePlayback();}});addWeighted(controls,shuffle);addWeighted(controls,icon("❮❮","Faixa anterior",()->skipTrack(-1)));playerPlay=button("▶",true,this::togglePlay);playerPlay.setContentDescription("Reproduzir ou pausar");playerPlay.setBackground(bg(BLUE,100));((Icons)playerPlay).glyphSize=48;controls.addView(playerPlay,new LinearLayout.LayoutParams(dp(84),dp(84)));addWeighted(controls,icon("❯❯","Próxima faixa",()->skipTrack(1)));repeat=icon("↻","Alternar repetição",()->{if(controller!=null){controller.setRepeatMode((controller.getRepeatMode()+1)%3);updatePlayback();}});addWeighted(controls,repeat);float controlShift=Math.min(18f,Math.max(0f,(width/getResources().getDisplayMetrics().density-136f)/8f-14f));for(int k=0;k<controls.getChildCount();k++){View control=controls.getChildAt(k);if(k!=2)control.setTranslationX(dp(k<2?-controlShift:controlShift));if((k==1||k==3)&&control instanceof Icons)((Icons)control).glyphSize=40;}base.addView(controls);gap(base,(int)(36*rhythm));
        playerStatus=text("",12,MUTED,false);playerStatus.setGravity(Gravity.CENTER);base.addView(playerStatus);LinearLayout actions=row();for(String[] a:new String[][]{{"queue","Fila"},{"volume","Volume"},{"lyrics","Letras"}}){Runnable click=a[0].equals("queue")?this::queueDialog:a[0].equals("volume")?this::volume:this::lyricsDialog;actions.addView(action(a[0],a[1],click),new LinearLayout.LayoutParams(0,-2,1));}base.addView(actions);lyricText=text("",17,INK,false);
        playerDialog.setOnDismissListener(d->{if(video!=null)video.setPlayer(null);video=null;cover=null;playerTitle=null;lyricText=null;displayedUri="";visualTrack=null;previousCover=null;nextCover=null;if(trackMotion!=null)trackMotion.cancel();playerMedia=null;playerSurface=null;closingPlayer=false;playerDialog=null;});base.setFocusableInTouchMode(true);playerDialog.show();win.setLayout(-1,-1);displayedUri="";updatePlayback();base.requestFocus();scroll.post(()->{scroll.scrollTo(0,0);scroll.setTranslationY(scroll.getHeight());scroll.animate().translationY(0).setDuration(MotionCurves.duration(600)).setInterpolator(MotionCurves.OPEN).start();});
    }
    private void updatePlayback(){
        if(controller==null)return;Track t=current();boolean playing=controller.isPlaying();miniPlay.setText(playing?"Ⅱ":"▶");
        if(t==null){label(miniTitle,"Escolha sua primeira música");label(miniSub,"Tudo fica no seu aparelho");if(playerDialog!=null)playerDialog.dismiss();return;}if(!t.title.contentEquals(miniTitle.getText()))label(miniTitle,t.title);if(!t.artist.contentEquals(miniSub.getText()))label(miniSub,t.artist);if(miniProgress!=null)miniProgress.setProgress(controller.getDuration()>0?(int)(controller.getCurrentPosition()*1000/controller.getDuration()):0);miniArt.track(t);if(playerTitle==null)return;
        label(playerTitle,t.title);label(playerArtist,t.artist);playerPlay.setText(playing?"Ⅱ":"▶");favorite.setText(store.favorites().contains(t.uri)?"♥︎":"♡");favorite.setTextColor(store.favorites().contains(t.uri)?BLUE:INK);
        shuffle.setTextColor(controller.getShuffleModeEnabled()?BLUE:MUTED);repeat.setText(controller.getRepeatMode()==Player.REPEAT_MODE_ONE?"↻¹":"↻");repeat.setTextColor(controller.getRepeatMode()==Player.REPEAT_MODE_OFF?MUTED:BLUE);
        long duration=controller.getDuration();if(duration<0)duration=t.duration;long position=controller.getCurrentPosition();if(!dragging){seek.setProgress(duration<=0?0:(int)(position*1000/duration));label(elapsed,MusicLogic.time(position));}label(total,MusicLogic.time(duration));
        String status=controller.getPlaybackState()==Player.STATE_BUFFERING?"Preparando arquivo…":controller.getPlayerError()!=null?"Arquivo indisponível ou formato não suportado":"";
        if(PlaybackService.active!=null&&PlaybackService.active.timerRemaining()>0)status+=" · pausa em "+MusicLogic.time(PlaybackService.active.timerRemaining());if(controller.getPlaybackParameters().speed!=1f)status+="  "+controller.getPlaybackParameters().speed+"×";label(playerStatus,status);playerStatus.setVisibility(status.isEmpty()?View.GONE:View.VISIBLE);
        if(visualTrack==null||!visualTrack.uri.equals(t.uri)){animateTrack(visualTrack,t);visualTrack=t;}else cover.track(t);if(!displayedUri.equals(t.uri)){displayedUri=t.uri;video.setVisibility(t.video?View.VISIBLE:View.GONE);cover.setVisibility(t.video?View.GONE:View.VISIBLE);if(playerDialog!=null&&playerDialog.getWindow()!=null){if(t.video)playerDialog.getWindow().addFlags(WindowManager.LayoutParams.FLAG_KEEP_SCREEN_ON);else playerDialog.getWindow().clearFlags(WindowManager.LayoutParams.FLAG_KEEP_SCREEN_ON);}String raw=store.lyric(t.uri);lyricLines=MusicLogic.lyrics(raw);lastLyric=-2;lyricText.setTextColor(MUTED);if(lyricLines.isEmpty())lyricText.setText(raw.isEmpty()?"Adicione uma letra local para acompanhar.":raw);}
        if(!lyricLines.isEmpty()){int index=MusicLogic.lyricIndex(lyricLines,position);if(index!=lastLyric){lastLyric=index;StringBuilder lines=new StringBuilder();int first=Math.max(0,index);for(int i=first;i<Math.min(first+3,lyricLines.size());i++)lines.append(lyricLines.get(i).text).append("\n");lyricText.setText(lines.toString().trim());lyricText.setTextColor(BLUE);}}
    }
    private View action(String glyph,String label,Runnable click){LinearLayout item=col();item.setGravity(Gravity.CENTER);Button b=icon(glyph,label,click);GradientDrawable circle=bg(0xff17283D,60);circle.setStroke(dp(1),0xff2A405B);b.setBackground(circle);item.addView(b,new LinearLayout.LayoutParams(dp(54),dp(54)));gap(item,8);TextView text=text(label,13,INK,false);text.setGravity(Gravity.CENTER);item.addView(text);item.setOnClickListener(v->click.run());return item;}
    private void playerOptions(){new VolumeDialogBuilder(this).setTitle("Opções de reprodução").setItems(new String[]{"Equalizador","Temporizador","Velocidade","Opções da música"},(d,w)->{if(w==0)effects();else if(w==1)timer();else if(w==2)speed();else if(current()!=null)trackMenu(current());}).show();}
    private void styleSlider(SeekBar slider,int thumbSize,int trackSize){
        GradientDrawable thumb=bg(BLUE,100);thumb.setSize(dp(thumbSize),dp(thumbSize));slider.setThumb(thumb);slider.setThumbOffset(dp(thumbSize/2f));slider.setSplitTrack(false);
        int edge=dp(thumbSize/2f+2);slider.setPadding(edge,0,edge,0);slider.setBackground(null);slider.setTickMark(null);
        GradientDrawable track=bg(0xff2B405C,4),fill=bg(BLUE,4);track.setSize(1,dp(trackSize));fill.setSize(1,dp(trackSize));
        android.graphics.drawable.ClipDrawable clip=new android.graphics.drawable.ClipDrawable(fill,Gravity.LEFT,android.graphics.drawable.ClipDrawable.HORIZONTAL);
        android.graphics.drawable.LayerDrawable layers=new android.graphics.drawable.LayerDrawable(new android.graphics.drawable.Drawable[]{track,clip});layers.setId(0,android.R.id.background);layers.setId(1,android.R.id.progress);layers.setLayerGravity(0,Gravity.CENTER_VERTICAL);layers.setLayerGravity(1,Gravity.CENTER_VERTICAL);layers.setLayerHeight(0,dp(trackSize));layers.setLayerHeight(1,dp(trackSize));slider.setProgressDrawable(layers);
    }
    private void requestGain(int value,java.util.function.Consumer<Boolean> completion){
        int selected=MusicLogic.clampGain(value);
        PlaybackService active=PlaybackService.active;
        if(active==null||active.player.getAudioSessionId()<=0){toast("Inicie uma música. Efeito indisponível nesta saída.");completion.accept(false);return;}
        Runnable apply=()->{PlaybackService current=PlaybackService.active;boolean ok=current!=null&&current.setGain(selected);if(!ok)toast("O Android não aceitou este ganho nesta saída de áudio");completion.accept(ok);};
        if(MusicLogic.gainMillibels(selected)<=6000||store.prefs.getBoolean("extreme_gain_ack_v1",false)){apply.run();return;}
        if(gainWarning!=null&&gainWarning.isShowing()){completion.accept(false);return;}
        if(quickVolume!=null)quickVolume.dismiss();
        gainWarning=new AlertDialog.Builder(this).setTitle("Ativar ganho extremo?")
            .setMessage("O nível 300% solicita até +88 dB de ganho digital. Isso não é uma medição do volume acústico.\n\nPode causar distorção intensa, danificar o alto-falante e prejudicar sua audição, especialmente com fones. Comece com o volume do aparelho baixo. O Android pode limitar ou recusar o efeito.")
            .setNegativeButton("Cancelar",(d,w)->completion.accept(false))
            .setPositiveButton("Entendo, ativar",(d,w)->{store.prefs.edit().putBoolean("extreme_gain_ack_v1",true).apply();apply.run();})
            .setOnCancelListener(d->completion.accept(false)).create();
        gainWarning.setOnKeyListener((d,key,event)->volumeKey(event,getWindow().getDecorView()));
        gainWarning.setOnDismissListener(d->gainWarning=null);
        gainWarning.show();
        gainWarning.getButton(AlertDialog.BUTTON_POSITIVE).setTextColor(BLUE);
    }
    private void volume(){
        android.media.AudioManager audio=(android.media.AudioManager)getSystemService(AUDIO_SERVICE);Dialog dialog=new KeyAwareDialog();LinearLayout box=col();box.setPadding(dp(26),dp(12),dp(26),dp(43));GradientDrawable sheet=new GradientDrawable(GradientDrawable.Orientation.TL_BR,new int[]{0xff101D30,0xff101D2F});sheet.setCornerRadii(new float[]{dp(22),dp(22),dp(22),dp(22),0,0,0,0});box.setBackground(sheet);
        View handle=new View(this);handle.setBackground(bg(0xff57708F,4));handle.setContentDescription("Fechar volume");handle.setOnClickListener(v->dialog.dismiss());LinearLayout.LayoutParams hp=new LinearLayout.LayoutParams(dp(44),dp(4));hp.gravity=Gravity.CENTER_HORIZONTAL;box.addView(handle,hp);gap(box,24);box.addView(text("Volume",26,INK,true));gap(box,15);
        LinearLayout normal=row();android.widget.ImageView speaker=new android.widget.ImageView(this);speaker.setImageDrawable(Icons.named(this,"volume"));normal.addView(speaker,new LinearLayout.LayoutParams(dp(26),dp(26)));SeekBar volume=new SeekBar(this);volume.setMax(audio.getStreamMaxVolume(android.media.AudioManager.STREAM_MUSIC));volume.setProgress(audio.getStreamVolume(android.media.AudioManager.STREAM_MUSIC));volume.setContentDescription("Volume do aparelho");volume.setProgressTintList(ColorStateList.valueOf(BLUE));volume.setThumbTintList(ColorStateList.valueOf(BLUE));styleSlider(volume,20,6);normal.addView(volume,new LinearLayout.LayoutParams(0,dp(48),1));TextView level=text("",16,MUTED,false);level.setGravity(Gravity.RIGHT);normal.addView(level,new LinearLayout.LayoutParams(dp(52),-2));box.addView(normal);gap(box,21);line(box,0xff1A2A40);gap(box,23);
        box.addView(text("Amplificação",18,INK,true));gap(box,8);LinearLayout amplification=row();LinearLayout sliderBlock=col();LinearLayout limits=row();addWeighted(limits,text("100%",13,MUTED,false));limits.addView(text("300%",13,MUTED,false));sliderBlock.addView(limits);SeekBar gain=new SeekBar(this);gain.setMax(3);gain.setProgress(MusicLogic.gainPresetIndex(store.prefs.getInt("gain_percent",100)));gain.setContentDescription("Amplificação de 100 a 300 por cento");gain.setProgressTintList(ColorStateList.valueOf(BLUE));gain.setThumbTintList(ColorStateList.valueOf(BLUE));styleSlider(gain,20,6);sliderBlock.addView(gain,new LinearLayout.LayoutParams(-1,dp(48)));amplification.addView(sliderBlock,new LinearLayout.LayoutParams(0,-2,1));TextView gainValue=text(MusicLogic.gainPresetPercent(gain.getProgress())+"%",17,BLUE,true);gainValue.setGravity(Gravity.RIGHT);amplification.addView(gainValue,new LinearLayout.LayoutParams(dp(70),-2));box.addView(amplification);gap(box,0);TextView note=text("Pode distorcer em volumes altos.",12,MUTED,false);box.addView(note);gap(box,26);
        LinearLayout eq=row();eq.setPadding(dp(20),0,dp(16),0);eq.setBackground(bg(0xff182B42,17));eq.setOnClickListener(v->effects());eq.setContentDescription("Equalizador");android.widget.ImageView eqIcon=new android.widget.ImageView(this);eqIcon.setImageDrawable(Icons.named(this,"equalizer"));eq.addView(eqIcon,new LinearLayout.LayoutParams(dp(26),dp(26)));TextView eqText=text("Equalizador",16,INK,true);eqText.setPadding(dp(18),0,0,0);addWeighted(eq,eqText);eq.addView(icon("right","Abrir equalizador",this::effects),new LinearLayout.LayoutParams(dp(24),dp(48)));box.addView(eq,new LinearLayout.LayoutParams(-1,dp(74)));
        PlaybackService service=PlaybackService.active;if(service==null||service.player.getAudioSessionId()<=0){gain.setEnabled(false);note.setText("Inicie uma música. Efeito sujeito ao suporte do aparelho.");}
        gain.setOnSeekBarChangeListener(new SeekBar.OnSeekBarChangeListener(){public void onStartTrackingTouch(SeekBar s){}public void onStopTrackingTouch(SeekBar s){}public void onProgressChanged(SeekBar s,int n,boolean user){if(user){requestGain(MusicLogic.gainPresetPercent(n),ok->{int selected=MusicLogic.clampGain(store.prefs.getInt("gain_percent",100));gain.setProgress(MusicLogic.gainPresetIndex(selected));gainValue.setText(selected+"%");note.setText(selected==300?"Ganho extremo ativo. Pode distorcer intensamente.":"Pode distorcer em volumes altos.");});}}});
        volume.setEnabled(!audio.isVolumeFixed());volume.setOnSeekBarChangeListener(new SeekBar.OnSeekBarChangeListener(){public void onStartTrackingTouch(SeekBar s){}public void onStopTrackingTouch(SeekBar s){}public void onProgressChanged(SeekBar s,int n,boolean user){if(user)try{audio.setStreamVolume(android.media.AudioManager.STREAM_MUSIC,n,0);}catch(SecurityException ignored){}}});
        ScrollView scroll=new ScrollView(this);scroll.setVerticalScrollBarEnabled(false);scroll.addView(box);dialog.setContentView(scroll);Window win=dialog.getWindow();win.setBackgroundDrawableResource(android.R.color.transparent);win.addFlags(WindowManager.LayoutParams.FLAG_DIM_BEHIND);win.setDimAmount(.5f);dialog.show();win.setLayout(-1,-2);win.setGravity(Gravity.BOTTOM);dialog.setCanceledOnTouchOutside(true);
        Runnable sync=new Runnable(){public void run(){if(!dialog.isShowing())return;int value=audio.getStreamVolume(android.media.AudioManager.STREAM_MUSIC);if(!volume.isPressed())volume.setProgress(value);label(level,Math.round(value*100f/Math.max(1,volume.getMax()))+"%");if(!gain.isPressed()){int selected=MusicLogic.clampGain(store.prefs.getInt("gain_percent",100));gain.setProgress(MusicLogic.gainPresetIndex(selected));label(gainValue,selected+"%");}PlaybackService active=PlaybackService.active;gain.setEnabled(active!=null&&active.player.getAudioSessionId()>0);handler.postDelayed(this,500);}};handler.post(sync);dialog.setOnDismissListener(d->handler.removeCallbacks(sync));
    }
    private Comparator<Track> trackOrder(int mode,boolean reverse){
        Comparator<Track> result=mode==1?Comparator.comparingLong((Track t)->t.added).reversed():mode==2?Comparator.comparing(t->MusicLogic.normalize(t.artist)):mode==3?Comparator.comparingLong((Track t)->t.duration).reversed():Comparator.comparing(t->MusicLogic.normalize(t.title));
        result=result.thenComparing(t->MusicLogic.normalize(t.title)).thenComparing(t->t.uri);return reverse?result.reversed():result;
    }
    private void selectPlaylistTracks(){
        if(group==null)return;String playlist=group;hideKeyboard();Set<String> existing=new HashSet<>(store.playlist(playlist)),selected=new LinkedHashSet<>();
        Dialog dialog=new KeyAwareDialog();LinearLayout box=col();box.setPadding(dp(20),dp(20),dp(20),dp(14));box.setBackground(bg(0xff14243A,24));
        LinearLayout heading=row();addWeighted(heading,text("Adicionar músicas",23,INK,true));heading.addView(icon("down","Fechar seleção",dialog::dismiss),new LinearLayout.LayoutParams(dp(44),dp(44)));box.addView(heading);gap(box,12);
        EditText find=new EditText(this);find.setSingleLine();find.setHint("Buscar na biblioteca");find.setTextSize(15);find.setTextColor(INK);find.setHintTextColor(MUTED);find.setPadding(dp(14),0,dp(14),0);find.setBackground(bg(CARD,14));box.addView(find,new LinearLayout.LayoutParams(-1,dp(48)));gap(box,8);
        LinearLayout options=row();TextView summary=text("",12,MUTED,false);addWeighted(options,summary);Button order=button("Ordenar",false,()->{});options.addView(order,new LinearLayout.LayoutParams(-2,dp(44)));box.addView(options);gap(box,8);
        List<Track> candidates=new ArrayList<>();ListView choices=new ListView(this);choices.setDivider(null);box.addView(choices,new LinearLayout.LayoutParams(-1,0,1));
        int[] mode={store.prefs.getInt("playlist_picker_sort",0)};boolean[] reversed={store.prefs.getBoolean("playlist_picker_reverse",false)};String[] modes={"Título","Adicionadas recentemente","Artista","Duração"};
        BaseAdapter picker=new BaseAdapter(){
            public int getCount(){return candidates.size();}public Object getItem(int i){return candidates.get(i);}public long getItemId(int i){return i;}
            public View getView(int i,View reused,ViewGroup parent){Track t=candidates.get(i);TrackRow h=reused!=null&&reused.getTag() instanceof TrackRow?(TrackRow)reused.getTag():new TrackRow();h.art.track(t);h.title.setText(t.title);h.detail.setText(existing.contains(t.uri)?"Já adicionada":t.artist);h.more.setVisibility(View.GONE);
                CheckBox check=h.row.findViewWithTag("selection");if(check==null){check=new CheckBox(MainActivity.this);check.setTag("selection");check.setClickable(false);check.setFocusable(false);check.setImportantForAccessibility(View.IMPORTANT_FOR_ACCESSIBILITY_NO);h.row.addView(check);}check.setChecked(existing.contains(t.uri)||selected.contains(t.uri));check.setEnabled(!existing.contains(t.uri));h.row.setAlpha(existing.contains(t.uri)?.55f:1f);
                h.row.setContentDescription(t.title+(existing.contains(t.uri)?", já adicionada":selected.contains(t.uri)?", selecionada":", não selecionada"));h.row.setOnClickListener(v->{if(existing.contains(t.uri))return;if(!selected.add(t.uri))selected.remove(t.uri);summary.setText(selected.size()+" selecionadas · "+candidates.size()+" músicas");notifyDataSetChanged();});return h.row;}
        };
        choices.setAdapter(picker);Runnable filterPicker=()->{candidates.clear();String q=MusicLogic.normalize(find.getText().toString());for(Track t:library)if(!t.video&&MusicLogic.normalize(t.title+" "+t.artist+" "+t.album).contains(q))candidates.add(t);candidates.sort(trackOrder(mode[0],reversed[0]));picker.notifyDataSetChanged();summary.setText(candidates.isEmpty()?"Nenhuma música encontrada":selected.size()+" selecionadas · "+candidates.size()+" músicas");order.setText("Ordenar "+(reversed[0]?"↑":"↓"));};
        order.setOnClickListener(v->new VolumeDialogBuilder(this).setTitle("Ordenar músicas · toque novamente para inverter").setSingleChoiceItems(modes,mode[0],(d,w)->{reversed[0]=mode[0]==w?!reversed[0]:false;mode[0]=w;store.prefs.edit().putInt("playlist_picker_sort",w).putBoolean("playlist_picker_reverse",reversed[0]).apply();filterPicker.run();choices.setSelection(0);d.dismiss();}).setNegativeButton("Fechar",null).show());
        find.addTextChangedListener(new TextWatcher(){public void beforeTextChanged(CharSequence s,int a,int c,int n){}public void onTextChanged(CharSequence s,int a,int b,int c){filterPicker.run();}public void afterTextChanged(Editable e){}});filterPicker.run();gap(box,12);
        LinearLayout actions=row();addWeighted(actions,button("Cancelar",false,dialog::dismiss));View space=new View(this);actions.addView(space,new LinearLayout.LayoutParams(dp(12),1));addWeighted(actions,button("Adicionar",true,()->{if(selected.isEmpty()){toast("Selecione pelo menos uma música");return;}List<Track> ordered=new ArrayList<>(library);ordered.sort(trackOrder(mode[0],reversed[0]));for(Track t:ordered)if(selected.contains(t.uri))store.addToPlaylist(playlist,t);dialog.dismiss();render();toast(selected.size()+" músicas adicionadas");}));box.addView(actions);
        dialog.setContentView(box);Window win=dialog.getWindow();win.setBackgroundDrawableResource(android.R.color.transparent);win.setSoftInputMode(WindowManager.LayoutParams.SOFT_INPUT_STATE_ALWAYS_HIDDEN|WindowManager.LayoutParams.SOFT_INPUT_ADJUST_RESIZE);dialog.show();win.setLayout(Math.min(getResources().getDisplayMetrics().widthPixels-dp(16),dp(600)),(int)(getResources().getDisplayMetrics().heightPixels*.88f));win.setGravity(Gravity.BOTTOM);
    }
    private void installChrome(View body,View scroller){
        LinearLayout chrome=col();if(appHeader.getParent()!=null)((ViewGroup)appHeader.getParent()).removeView(appHeader);chrome.addView(appHeader);
        while(content.getChildCount()>0){View child=content.getChildAt(0);content.removeViewAt(0);if(child!=body)chrome.addView(child);}
        content.addView(new CollapsingChrome(this,chrome,body,scroller),new LinearLayout.LayoutParams(-1,0,1));
    }
    private void installMiniSwipe(View target){
        target.setOnTouchListener(new View.OnTouchListener(){float x,y;boolean moved;
            public boolean onTouch(View v,MotionEvent e){switch(e.getActionMasked()){
                case MotionEvent.ACTION_DOWN:x=e.getRawX();y=e.getRawY();moved=false;return true;
                case MotionEvent.ACTION_MOVE:if(y-e.getRawY()>dp(8)&&Math.abs(e.getRawY()-y)>Math.abs(e.getRawX()-x)){moved=true;v.setTranslationY(Math.max(-dp(28),(e.getRawY()-y)*.3f));}return true;
                case MotionEvent.ACTION_UP:v.animate().translationY(0).setDuration(MotionCurves.duration(300)).start();if(moved&&y-e.getRawY()>dp(19.2f))showPlayer();else if(!moved)v.performClick();return true;
                case MotionEvent.ACTION_CANCEL:v.animate().translationY(0).setDuration(MotionCurves.duration(300)).start();return true;
            }return false;}
        });
    }
    private void minimizePlayer(){
        if(playerDialog==null||playerSurface==null||closingPlayer)return;closingPlayer=true;Dialog current=playerDialog;
        playerSurface.animate().translationY(playerSurface.getHeight()).setDuration(MotionCurves.duration(400)).setInterpolator(MotionCurves.CLOSE).withEndAction(current::dismiss).start();
    }
    private boolean skipTrack(int direction){
        if(controller==null)return false;
        if(direction>0&&!controller.hasNextMediaItem()||direction<0&&!controller.hasPreviousMediaItem()){toast(direction>0?"Última música da fila":"Primeira música da fila");return false;}
        pendingTrackDirection=direction;if(direction>0)controller.seekToNextMediaItem();else controller.seekToPreviousMediaItem();return true;
    }
    private void prepareNeighborCovers(){
        if(playerMedia==null||controller==null)return;int width=playerMedia.getWidth();
        int left=controller.getPreviousMediaItemIndex(),right=controller.getNextMediaItemIndex();
        previousCover.setVisibility(left==C.INDEX_UNSET?View.GONE:View.VISIBLE);nextCover.setVisibility(right==C.INDEX_UNSET?View.GONE:View.VISIBLE);
        if(left!=C.INDEX_UNSET)previousCover.track(Track.item(controller.getMediaItemAt(left)));if(right!=C.INDEX_UNSET)nextCover.track(Track.item(controller.getMediaItemAt(right)));
        previousCover.setTranslationX(-width);nextCover.setTranslationX(width);previousCover.setScaleX(1);previousCover.setScaleY(1);nextCover.setScaleX(1);nextCover.setScaleY(1);
    }
    private void animateTrack(Track old,Track next){
        if(cover==null||playerMedia==null)return;cover.track(next);
        if(old==null||old.video||next.video||playerMedia.getWidth()==0){pendingTrackDirection=0;FrameLayout expected=playerMedia;expected.post(()->{if(playerMedia==expected)prepareNeighborCovers();});return;}
        FrameLayout media=playerMedia;BrandView incoming=cover;int direction=pendingTrackDirection==0?1:pendingTrackDirection;pendingTrackDirection=0;
        if(trackMotion!=null)trackMotion.cancel();incoming.animate().cancel();for(int i=media.getChildCount()-1;i>=0;i--){View child=media.getChildAt(i);if("outgoing-cover".equals(child.getTag())){child.animate().cancel();media.removeView(child);}}
        previousCover.setVisibility(View.GONE);nextCover.setVisibility(View.GONE);
        BrandView outgoing=new BrandView(this);outgoing.track(old);outgoing.setTag("outgoing-cover");media.addView(outgoing,new FrameLayout.LayoutParams(-1,-1));
        int distance=media.getWidth();float start=Math.max(0,Math.min(.95f,-direction*incoming.getTranslationX()/distance));
        android.animation.ValueAnimator motion=android.animation.ValueAnimator.ofFloat(start,1f);trackMotion=motion;
        motion.setDuration(MotionCurves.duration((long)(300*(1-start))));motion.setInterpolator(MotionCurves.TRACK);
        motion.addUpdateListener(animation->{float progress=(float)animation.getAnimatedValue();outgoing.setTranslationX(-direction*distance*progress);incoming.setTranslationX(direction*distance*(1-progress));float outScale=1-.1f*Math.min(1,progress/.3f),inScale=.9f+.1f*Math.max(0,(progress-.7f)/.3f);outgoing.setScaleX(outScale);outgoing.setScaleY(outScale);incoming.setScaleX(inScale);incoming.setScaleY(inScale);});
        motion.addListener(new android.animation.AnimatorListenerAdapter(){boolean cancelled;public void onAnimationCancel(android.animation.Animator a){cancelled=true;}public void onAnimationEnd(android.animation.Animator a){media.removeView(outgoing);if(!cancelled&&playerMedia==media){incoming.setTranslationX(0);incoming.setScaleX(1);incoming.setScaleY(1);prepareNeighborCovers();}}});motion.start();
    }
    private final class KeyAwareDialog extends androidx.activity.ComponentDialog {
        KeyAwareDialog(){super(MainActivity.this);configureBack();}KeyAwareDialog(int theme){super(MainActivity.this,theme);configureBack();}private void configureBack(){getOnBackPressedDispatcher().addCallback(new OnBackPressedCallback(true){public void handleOnBackPressed(){if(KeyAwareDialog.this==playerDialog)minimizePlayer();else dismiss();}});}
        @Override public boolean onKeyDown(int key,KeyEvent event){return volumeKey(event,getWindow().getDecorView())||super.onKeyDown(key,event);}@Override public boolean onKeyUp(int key,KeyEvent event){return volumeKey(event,getWindow().getDecorView())||super.onKeyUp(key,event);}

    }
    private final class VolumeDialogBuilder extends AlertDialog.Builder {
        VolumeDialogBuilder(Context context){super(context);}
        @Override public AlertDialog create(){AlertDialog dialog=super.create();dialog.setOnKeyListener((d,key,event)->volumeKey(event,dialog.getWindow().getDecorView()));return dialog;}
    }
    @Override public boolean onKeyDown(int key,KeyEvent event){return volumeKey(event,getWindow().getDecorView())||super.onKeyDown(key,event);}@Override public boolean onKeyUp(int key,KeyEvent event){return volumeKey(event,getWindow().getDecorView())||super.onKeyUp(key,event);}
    private boolean volumeKey(KeyEvent event,View anchor){
        int key=event.getKeyCode();if(key!=KeyEvent.KEYCODE_VOLUME_UP&&key!=KeyEvent.KEYCODE_VOLUME_DOWN&&key!=KeyEvent.KEYCODE_VOLUME_MUTE)return false;
        if(event.getAction()!=KeyEvent.ACTION_DOWN)return true;
        if(gainWarning!=null&&gainWarning.isShowing()&&key==KeyEvent.KEYCODE_VOLUME_UP)return true;
        android.media.AudioManager audio=(android.media.AudioManager)getSystemService(AUDIO_SERVICE);int maximum=audio.getStreamMaxVolume(android.media.AudioManager.STREAM_MUSIC),level=audio.getStreamVolume(android.media.AudioManager.STREAM_MUSIC);int index=MusicLogic.gainPresetIndex(store.prefs.getInt("gain_percent",100));PlaybackService service=PlaybackService.active;
        if(!audio.isVolumeFixed())try{
            if(key==KeyEvent.KEYCODE_VOLUME_MUTE){audio.adjustStreamVolume(android.media.AudioManager.STREAM_MUSIC,android.media.AudioManager.ADJUST_TOGGLE_MUTE,0);}
            else if(key==KeyEvent.KEYCODE_VOLUME_DOWN&&index>0){if(service==null||!service.setGain(MusicLogic.gainPresetPercent(index-1))){store.prefs.edit().putInt("gain_percent",100).apply();audio.adjustStreamVolume(android.media.AudioManager.STREAM_MUSIC,android.media.AudioManager.ADJUST_LOWER,0);}}
            else if(key==KeyEvent.KEYCODE_VOLUME_UP&&level>=maximum){if(service!=null)requestGain(MusicLogic.gainPresetPercent(Math.min(3,index+1)),ok->syncQuickVolume());}
            else audio.adjustStreamVolume(android.media.AudioManager.STREAM_MUSIC,key==KeyEvent.KEYCODE_VOLUME_UP?android.media.AudioManager.ADJUST_RAISE:android.media.AudioManager.ADJUST_LOWER,0);
        }catch(SecurityException ignored){toast("O Android limitou o ajuste de volume nesta saída");}
        showQuickVolume(anchor);return true;
    }
    private void showQuickVolume(View anchor){
        if(gainWarning!=null&&gainWarning.isShowing())return;
        if(quickVolume!=null&&quickVolume.isShowing()){syncQuickVolume();scheduleQuickHide();return;}
        android.media.AudioManager audio=(android.media.AudioManager)getSystemService(AUDIO_SERVICE);LinearLayout box=col();box.setPadding(dp(20),dp(16),dp(20),dp(14));GradientDrawable background=bg(0xff14243A,22);background.setStroke(dp(1),0xff355275);box.setBackground(background);box.setElevation(dp(12));
        LinearLayout head=row();addWeighted(head,text("Volume",19,INK,true));head.addView(icon("down","Fechar barra de volume",()->{if(quickVolume!=null)quickVolume.dismiss();}),new LinearLayout.LayoutParams(dp(36),dp(36)));box.addView(head);
        quickLevelText=text("",13,MUTED,false);box.addView(quickLevelText);quickLevel=new SeekBar(this);quickLevel.setMax(audio.getStreamMaxVolume(android.media.AudioManager.STREAM_MUSIC));quickLevel.setContentDescription("Volume rápido do aparelho");styleSlider(quickLevel,18,4);box.addView(quickLevel,new LinearLayout.LayoutParams(-1,dp(42)));quickLevel.setEnabled(!audio.isVolumeFixed());
        quickGainText=text("",14,BLUE,true);box.addView(quickGainText);quickGain=new SeekBar(this);quickGain.setMax(3);quickGain.setContentDescription("Amplificação rápida: 100, 150, 200 ou 300 por cento");styleSlider(quickGain,18,4);box.addView(quickGain,new LinearLayout.LayoutParams(-1,dp(42)));TextView note=text("100% · 150% · 200% · 300%",12,MUTED,false);box.addView(note);
        quickLevel.setOnSeekBarChangeListener(new SeekBar.OnSeekBarChangeListener(){public void onStartTrackingTouch(SeekBar s){adjustingQuickVolume=true;handler.removeCallbacks(hideQuickVolume);}public void onStopTrackingTouch(SeekBar s){adjustingQuickVolume=false;scheduleQuickHide();}public void onProgressChanged(SeekBar s,int n,boolean user){if(user){try{audio.setStreamVolume(android.media.AudioManager.STREAM_MUSIC,n,0);}catch(SecurityException ignored){}syncQuickVolume();}}});
        quickGain.setOnSeekBarChangeListener(new SeekBar.OnSeekBarChangeListener(){public void onStartTrackingTouch(SeekBar s){adjustingQuickVolume=true;handler.removeCallbacks(hideQuickVolume);}public void onStopTrackingTouch(SeekBar s){adjustingQuickVolume=false;scheduleQuickHide();}public void onProgressChanged(SeekBar s,int n,boolean user){if(user){requestGain(MusicLogic.gainPresetPercent(n),ok->{note.setText(store.prefs.getInt("gain_percent",100)==300?"Ganho extremo ativo.":"Ganho elevado: pode distorcer.");syncQuickVolume();});}}});
        Rect visible=new Rect();anchor.getWindowVisibleDisplayFrame(visible);int available=visible.width()>0?visible.width():getResources().getDisplayMetrics().widthPixels;quickVolume=new PopupWindow(box,Math.min(dp(340),available-dp(32)),-2,false);quickVolume.setBackgroundDrawable(bg(0xff14243A,22));quickVolume.setOutsideTouchable(true);quickVolume.setElevation(dp(12));quickVolume.setOnDismissListener(()->{handler.removeCallbacks(hideQuickVolume);adjustingQuickVolume=false;});quickVolume.showAtLocation(anchor,Gravity.TOP|Gravity.CENTER_HORIZONTAL,0,visible.top+dp(12));syncQuickVolume();scheduleQuickHide();
    }
    private void syncQuickVolume(){if(quickLevel==null||quickGain==null)return;android.media.AudioManager audio=(android.media.AudioManager)getSystemService(AUDIO_SERVICE);int value=audio.getStreamVolume(android.media.AudioManager.STREAM_MUSIC);quickLevel.setProgress(value);quickLevelText.setText("Aparelho · "+Math.round(value*100f/Math.max(1,quickLevel.getMax()))+"%");int gain=MusicLogic.gainPresetIndex(store.prefs.getInt("gain_percent",100));quickGain.setProgress(gain);quickGainText.setText("Amplificação · "+MusicLogic.gainPresetPercent(gain)+"%");}
    private void scheduleQuickHide(){handler.removeCallbacks(hideQuickVolume);handler.postDelayed(hideQuickVolume,3500);}
    private void speed(){if(controller==null)return;String[] labels={"0,5×","0,75×","1× · normal","1,25×","1,5×","1,75×","2×"};float[] values={.5f,.75f,1f,1.25f,1.5f,1.75f,2f};new VolumeDialogBuilder(this).setTitle("Velocidade").setItems(labels,(d,w)->controller.setPlaybackSpeed(values[w])).show();}
    private void timer(){if(PlaybackService.active==null){toast("Abra uma música para configurar o temporizador");return;}int[] times={0,5,15,30,45,60,90};new VolumeDialogBuilder(this).setTitle("Pausar automaticamente").setItems(new String[]{"Desativar","Em 5 minutos","Em 15 minutos","Em 30 minutos","Em 45 minutos","Em 1 hora","Em 1h30"},(d,w)->{if(PlaybackService.active!=null)PlaybackService.active.setTimer(times[w]);toast(times[w]==0?"Temporizador desativado":"Pausa em "+times[w]+" minutos");}).show();}
    private void effects(){
        PlaybackService service=PlaybackService.active;Equalizer eq=service==null?null:service.equalizer;
        if(eq==null){new VolumeDialogBuilder(this).setTitle("Equalizador").setMessage("Comece a reproduzir uma música. O equalizador depende da sessão de áudio e dos efeitos disponíveis no aparelho.").setPositiveButton("Entendi",null).show();return;}
        LinearLayout box=col();box.setPadding(dp(22),dp(12),dp(22),dp(12));Switch enable=new Switch(this);enable.setText("Equalizador ativo");enable.setChecked(store.prefs.getBoolean("eq_enabled",false));enable.setOnCheckedChangeListener((v,yes)->{store.prefs.edit().putBoolean("eq_enabled",yes).apply();service.applyEffects();});box.addView(enable);gap(box,16);
        try{short[] range=eq.getBandLevelRange();for(short b=0;b<eq.getNumberOfBands();b++){
            int hz=eq.getCenterFreq(b)/1000;short band=b;TextView label=text((hz>=1000?String.format(Locale.ROOT,"%.1f kHz",hz/1000f):hz+" Hz"),13,MUTED,false);box.addView(label);SeekBar slider=new SeekBar(this);slider.setMax(range[1]-range[0]);slider.setProgress(store.prefs.getInt("eq_band_"+b,0)-range[0]);slider.setContentDescription("Ganho em "+hz+" Hz");slider.setOnSeekBarChangeListener(new SeekBar.OnSeekBarChangeListener(){public void onStartTrackingTouch(SeekBar s){}public void onStopTrackingTouch(SeekBar s){}public void onProgressChanged(SeekBar s,int p,boolean user){if(user){int level=p+range[0];store.prefs.edit().putInt("eq_band_"+band,level).apply();service.applyEffects();label.setText(hz+" Hz · "+String.format(Locale.ROOT,"%+.1f dB",level/100f));}}});box.addView(slider,new LinearLayout.LayoutParams(-1,dp(48)));}
        }catch(RuntimeException e){toast("Efeito indisponível nesta sessão");return;}
        ScrollView scroll=new ScrollView(this);scroll.addView(box);new VolumeDialogBuilder(this).setTitle("Seu som").setView(scroll).setNeutralButton("Zerar bandas",(d,w)->{for(int b=0;b<32;b++)store.prefs.edit().putInt("eq_band_"+b,0).apply();service.applyEffects();}).setPositiveButton("Pronto",null).show();
    }
    private void queueDialog(){
        if(controller==null)return;ArrayList<String> labels=new ArrayList<>();for(int i=0;i<controller.getMediaItemCount();i++)labels.add((i==controller.getCurrentMediaItemIndex()?"▶  ":"")+(i+1)+". "+controller.getMediaItemAt(i).mediaMetadata.title);
        new VolumeDialogBuilder(this).setTitle("Fila · "+labels.size()+" faixas").setItems(labels.toArray(new String[0]),(d,w)->new VolumeDialogBuilder(this).setTitle(labels.get(w)).setItems(new String[]{"Tocar","Mover para a próxima posição","Remover da fila"},(a,b)->{if(controller==null||w>=controller.getMediaItemCount())return;if(b==0){controller.seekToDefaultPosition(w);controller.prepare();controller.play();}else if(b==1){int target=Math.min(controller.getMediaItemCount()-1,controller.getCurrentMediaItemIndex()+1);controller.moveMediaItem(w,target);}else controller.removeMediaItem(w);}).show()).setPositiveButton("Fechar",null).show();
    }
    private void pickLyrics(){Track t=current();if(t==null)return;pendingLyrics=t.uri;startActivityForResult(new Intent(Intent.ACTION_OPEN_DOCUMENT).setType("*/*").addCategory(Intent.CATEGORY_OPENABLE),51);}
    private void lyricsDialog(){Track t=current();if(t==null)return;String raw=store.lyric(t.uri);LinearLayout body=col();body.setPadding(dp(20),dp(12),dp(20),dp(20));if(lyricText==null)lyricText=text("",18,INK,false);if(lyricText.getParent()!=null)((ViewGroup)lyricText.getParent()).removeView(lyricText);lyricText.setText(raw.isEmpty()?"Adicione uma letra LRC ou TXT para acompanhar a música.":raw);body.addView(lyricText);displayedUri="";updatePlayback();ScrollView scroll=new ScrollView(this);scroll.addView(body);AlertDialog d=new VolumeDialogBuilder(this).setTitle("Letras").setView(scroll).setNeutralButton(raw.isEmpty()?"Adicionar letra":"Trocar letra",(dialog,w)->pickLyrics()).setNegativeButton(raw.isEmpty()?"Cancelar":"Remover",(dialog,w)->{if(!raw.isEmpty()){store.lyric(t.uri,"");displayedUri="";updatePlayback();}}).setPositiveButton("Fechar",null).create();d.setOnDismissListener(dialog->{if(lyricText!=null&&lyricText.getParent()==body)body.removeView(lyricText);});d.show();}
    @Override protected void onActivityResult(int request,int result,Intent data){super.onActivityResult(request,result,data);if(result!=RESULT_OK||data==null)return;
        if(request==50){List<Uri> uris=new ArrayList<>();if(data.getClipData()!=null)for(int i=0;i<data.getClipData().getItemCount();i++)uris.add(data.getClipData().getItemAt(i).getUri());else if(data.getData()!=null)uris.add(data.getData());for(Uri uri:uris){try{getContentResolver().takePersistableUriPermission(uri,Intent.FLAG_GRANT_READ_URI_PERMISSION);}catch(SecurityException ignored){}importTrack(uri,false);}return;}
        Uri uri=data.getData();if(uri==null)return;
        if(request==54&&!pendingArtwork.isEmpty()){try{getContentResolver().takePersistableUriPermission(uri,Intent.FLAG_GRANT_READ_URI_PERMISSION);}catch(SecurityException ignored){}store.prefs.edit().putString("art_override_"+pendingArtwork,uri.toString()).apply();Artwork.invalidate(pendingArtwork);pendingArtwork="";displayedUri="";filter();updatePlayback();if(PlaybackService.active!=null)PlaybackService.active.forceArtworkRefresh();toast("Capa atualizada");}
        if(request==51){String trackUri=pendingLyrics;if(trackUri.isEmpty())return;io.execute(()->{try{String raw=readText(uri,1024*1024);store.lyric(trackUri,raw);runOnUiThread(()->{displayedUri="";updatePlayback();toast("Letra salva no aparelho");});}catch(Exception e){runOnUiThread(()->toast("Não foi possível ler a letra. Use LRC ou TXT em UTF-8."));}});}
        if(request==52){io.execute(()->{try(OutputStream out=getContentResolver().openOutputStream(uri)){if(out==null)throw new IOException();out.write(store.backup().getBytes(StandardCharsets.UTF_8));runOnUiThread(()->toast("Backup exportado"));}catch(Exception e){runOnUiThread(()->toast("Não foi possível exportar o backup"));}});}
        if(request==53){io.execute(()->{try{String raw=readText(uri,8*1024*1024);store.restore(raw);runOnUiThread(()->{render();toast("Backup mesclado com suas coleções");});}catch(Exception e){runOnUiThread(()->toast("Backup inválido ou não acessível"));}});}
    }
    private String readText(Uri uri,int max)throws IOException{try(InputStream in=getContentResolver().openInputStream(uri);ByteArrayOutputStream out=new ByteArrayOutputStream()){if(in==null)throw new IOException();byte[] buffer=new byte[4096];int n;while((n=in.read(buffer))!=-1){if(out.size()+n>max)throw new IOException("Muito grande");out.write(buffer,0,n);}return out.toString(StandardCharsets.UTF_8.name());}}
}
